### ISSUE TITLE
SwiftUI

### ISSUE THREAD

**Issue by raul-aponte** [iosdevgdl/meetups#4]

**Comment by dcoria7** [comment]
Hola @raul-aponte, quisieras dar la charla de SwiftUI para este mes o para el siguiente?

**Comment by raul-aponte** [comment]
Hola, cualquier día, no tengo problema @dcoria7

**Comment by dcoria7** [comment]
Entonces te parece si nos platicas sobre SwiftUI para este mes? contactame por facebook en la pagina del grupo para los detalles porfa.
